# 2. 9벡터

In [2]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

## 2.9.2 벡더틩 정의

In [3]:
import numpy as np

In [5]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [6]:
print(x)

[1 2 3]


In [8]:
y = np.array([4, 5, 6])
print(x + y)

[5 7 9]


In [9]:
type(x)

numpy.ndarray

## 2.9.3 요소의 참조

In [15]:
x[0]

100

## 2.9.4 요소의 수정

In [16]:
x[0] = 100
print(x)

[100   2   3]


## 2.9.5 연속된 정수 벡터의 생성

In [17]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [18]:
print(np.arange(5, 10))

[5 6 7 8 9]


## 2.9.6 ndarray 형의 주의점

In [19]:
a = np.array([1, 1])
b = a
print('a =' + str(a))
print('b= ' + str(b))
b[0] = 100
print('b= ' + str(b))
print('a= ' + str(a))

a =[1 1]
b= [1 1]
b= [100   1]
a= [100   1]


In [20]:
a = np.array([1, 1])
b = a.copy()
print('a = ' + str(a))
print('b = ' + str(b))
b[0] = 100
print('b = ' + str(b))
print('a = ' + str(a))

a = [1 1]
b = [1 1]
b = [100   1]
a = [1 1]


# 2. 10 행렬

## 2.10.1 행렬의 정의

In [22]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

[[1 2 3]
 [4 5 6]]


## 2.10.2 행렬의 크기

In [26]:
x = np.array([[1, 2 ,3], [4, 5, 6]])
x.shape

(2, 3)

In [27]:
w, h = x.shape
print(w)
print(h)

2
3


## 2.10.3 요소의 참조

In [28]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x[1, 2]

6

## 2.10.4 요소의 수정

In [29]:
x = np.array([[1, 2 ,3], [4, 5, 6]])
x[1, 2] = 100
print(x)

[[  1   2   3]
 [  4   5 100]]


## 2.10.5 요소가 0과 1인 ndarray 만들기

In [30]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [31]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## 2.10.6 요소가 랜덤인 행렬 생성 

In [32]:
np.random.rand(2, 3)

array([[0.10250454, 0.00667978, 0.2307898 ],
       [0.00938211, 0.98436896, 0.598903  ]])

## 2.10.7 행렬의 크기 변경

In [34]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
a.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# 2.11 행렬(ndarray)의 사칙 연산

## 2.11.1 행렬의 사칙 연산

In [37]:
x = np.array([[4, 4, 4], [8, 8, 8]])
y = np.array([[1, 1, 1], [2, 2, 2]])
print(x + y)

[[ 5  5  5]
 [10 10 10]]


## 2.11.2 스칼라 X 행렬

In [38]:
x = np.array([[4, 4, 4], [8, 8, 8]])
print(10 * x)

[[40 40 40]
 [80 80 80]]


## 2.11.3 산술 함수 

In [39]:
x = np.array([[4, 4, 4], [8, 8, 8]])
print(np.exp(x))

[[  54.59815003   54.59815003   54.59815003]
 [2980.95798704 2980.95798704 2980.95798704]]


## 2.11.4 행렬 곱의 계산 

In [40]:
v = np.array([[1, 2, 3], [4, 5, 6]])
w = np.array([[1, 1], [2, 2], [3, 3]])
print(v.dot(w))

[[14 14]
 [32 32]]
