## 인공지능 빅데이터공학과 18118046 전효성

# 리스트 4-3-(1)

In [2]:
import numpy as np

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


# list 4-3-(3)

In [5]:
B = np.array([[7 , 8, 9], [10, 11, 12]])
print(B)

[[ 7  8  9]
 [10 11 12]]


# list 4-3-(4)

In [6]:
print(A + B)
print(A - B)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]


# 4.6.3 스칼라배
## list 4-3-(5)

In [7]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(2 * A)

[[ 2  4  6]
 [ 8 10 12]]


## list 3-4-(6)

In [8]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print(A.dot(B))

32


## list 3-4-(7)

In [9]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print(A * B)

[ 4 10 18]


## list 3-4-(8)

In [10]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print(A / B)

[0.25 0.4  0.5 ]


## list 3-4-(9)

In [13]:
A = np.array([[1, 2 ,3], [-1, -2, -3]])
B = np.array([[4, -4], [5, -5], [6, -6]])
print(A.dot(B))

[[ 32 -32]
 [-32  32]]


# 4.6.5 identity matrix
## list 4-3-(10)

In [14]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## list 3-4-(11)

In [19]:
A = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
I = np.identity(3)
print(A.dot(I))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# invertible matrix
## list 4-3-(12)

In [20]:
A = np.array([[1, 2], [3, 4]])
invA = np.linalg.inv(A)
print(invA)

[[-2.   1. ]
 [ 1.5 -0.5]]


# transpose matrix
## list 4-3-(13)

In [22]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print(A.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
