In [1]:
import numpy as np

In [2]:
a = list(range(10))

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
a = round(10 / 3, 3)

In [7]:
print(a)

3.333


In [8]:
x = np.array([1, 2, 3])

In [9]:
print(x)
x

[1 2 3]


array([1, 2, 3])

In [10]:
a = [1, 2]
b = [3, 4]
a + b

[1, 2, 3, 4]

In [11]:
a = np.array([1, 2])
b = np.array([3, 4])
print(a + b)
a + b


[4 6]


array([4, 6])

In [13]:
a = np.arange(10)

In [14]:
a = 1

array([1, 2])

In [67]:
c = np.zeros((3, 4, 4))
print(c)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [74]:
c.reshape(3, 2, 8)

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [78]:
x = np.arange(10)

In [79]:
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [80]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

ValueError: cannot reshape array of size 10 into shape (2,3)

In [82]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [89]:
x = x.reshape((2, 5))

In [90]:
x[:2, 2:3]

array([[2],
       [7]])

In [92]:
print(x > 3)

[[False False False False  True]
 [ True  True  True  True  True]]


In [112]:
d = np.random.randint(0, 10, 100)

In [113]:
d

array([6, 8, 2, 8, 4, 7, 3, 5, 0, 2, 0, 6, 1, 3, 0, 0, 0, 4, 7, 0, 6, 3,
       7, 5, 2, 9, 6, 9, 2, 4, 2, 4, 1, 3, 5, 4, 5, 7, 0, 9, 1, 5, 8, 6,
       4, 4, 8, 7, 3, 7, 3, 5, 0, 4, 6, 4, 2, 8, 3, 3, 5, 2, 9, 6, 6, 5,
       8, 3, 1, 2, 5, 2, 8, 4, 1, 1, 8, 0, 5, 9, 3, 0, 1, 0, 2, 8, 4, 8,
       4, 1, 9, 2, 0, 9, 6, 6, 0, 5, 2, 9])

In [1]:
import numpy as np
a = np.random.randint(1, 10, (2, 3))


In [2]:
print(a)

[[6 1 9]
 [9 3 5]]


In [3]:
c =np.arange(10)

In [4]:
print(c)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
c[8::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])