In [15]:
[1 ,2] + [3, 4]

[1, 2, 3, 4]

In [20]:
import numpy as np

In [24]:
x = np.array([1, 2, 3])

In [41]:
z = np.arange(10)
print(z)
type(z)

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [48]:
a = np.array([1, 1])
b = a
print(a)
print(b)
a[0] = 3
print(a)
print(b)
print(id(a), id(b))

[1 1]
[1 1]
[3 1]
[3 1]
140281417861200 140281417861200


In [51]:
c = [1, 2]
d = c.copy()
print(d)
print(c)
d[0] = 3
print(d)
print(c)
print('c address = ' , id(c) , ' d address = ' , id(d))

[1, 2]
[1, 2]
[3, 2]
[1, 2]
c address =  140281417834248  d address =  140281963533832


In [52]:
q = np.array([[1,2, 3], [4, 5,6]])

In [54]:
print(q)

[[1 2 3]
 [4 5 6]]
